version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "api/pom.xml" }}

      - run: cd api && mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "api/pom.xml" }}

      # run tests!
      - run: cd api && mvn package

      - store_test_results: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: target/surefire-reports

      - store_artifacts:
          path: api/target/autoform-api-0.0.1-SNAPSHOT.jar

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: api
          # Must be relative path from root
          paths:
            - target
  dockerise:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: api
      - setup_remote_docker
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: ls api

      # build the application image
      - run: cd api && docker build -t estragonthecat/autoform-api .

      - run: docker login -p $TOKEN_DOCKERHUB -u $USERNAME_DOCKERHUB

      # deploy the image
      - run: docker push estragonthecat/autoform-api

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - dockerise:
          requires:
            - build
